//
// Created by Foresstt on 28-Oct-17.
//

#ifndef PARALLELANDDISTRIBUTEDCOMPUTINGLAB4_FUNCTIONS_H
#define PARALLELANDDISTRIBUTEDCOMPUTINGLAB4_FUNCTIONS_H

void threadFunction1();

void threadFunction2();

void threadFunction3();

#endif //PARALLELANDDISTRIBUTEDCOMPUTINGLAB4_FUNCTIONS_H
